name: Build frontend CI

on: [push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x]
    runs-on: ${{ matrix.os }}
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run:  npm ci

    # - name: Lint
      # run:  npm run lint

    - name: Test
      run:  npm run test --coverage
        
    - name: Build Project
      run:  npm run build --if-present

    - name: List output files
      run:  ls build
